name: Node.js CI

on:
  push:
    branches: [ web ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: git branch -a
      - run: git switch web
      - run: npm install
      - run: npm run build
      - run: git stash
      - run: git switch gh-pages
      - run: git stash pop
      - run: git add ./
      - run: git commit -m "新页面"
      - run: git push -m gh-pages